[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.13.1"
junitVersion = "1.3.0"
junit = "4.13.2"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.10.01"
constraintlayout = "2.2.1"
coilCompose = "2.7.0"
converterGson = "2.11.0"
firebaseBom = "34.4.0"
gson = "2.11.0"
jaudiotagger = "3.0.1"
loggingInterceptor = "4.12.0"
material = "1.13.0"
media = "1.7.0"
media3Session = "1.8.0"
okhttp = "4.12.0"
paginate = "1.0.0"
paletteKtx = "1.0.0"
picasso = "2.71828"
recyclerview = "1.3.2"
retrofit = "2.11.0"
runtime = "1.7.6"
foundationLayout = "1.7.6"
media3Exoplayer = "1.8.0"
media3Ui = "1.4.0"
navigationCompose = "2.8.5"
navigationRuntimeKtx = "2.8.5"
sdpAndroid = "1.1.0"
shimmer = "0.5.0"
slidingrootnav = "1.1.1"
sspAndroid = "1.1.0"
swiperefreshlayout = "1.1.0"
ui = "1.7.6"
firebaseMessagingKtx = "24.1.2"
firebaseAnalytics = "22.5.0"
appcompat = "1.7.1"
googleGmsGoogleServices = "4.4.4"
material3 = "1.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "ui" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "ui" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "ui" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
com-github-yarolegovich-slidingrootnav = { group = "com.github.yarolegovich", name = "SlidingRootNav", version.ref = "slidingrootnav" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
